In [9]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

import  numpy as np
n=20 
ar1 =  np.arange(0, n)[::-1]

print(list(ar1))

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [39]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

import  numpy as np
n=16
ar1 =  np.arange(0, n)[::-1]

rows_n = int(n**(0.5))

if rows_n**2 == n:
    ar2 = ar1.reshape(rows_n,rows_n)

print(ar2)
print('сумма по диагонали=', ar2.trace())


[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
сумма по диагонали= 30


In [ ]:
""""
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
""""

In [45]:
#Задание 3
#Решите систему уравнений:

import  numpy as np
from numpy import linalg


a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
k = np.array([4, 12, -3])

linalg.solve(a, k)



array([ 0.46666667,  3.84444444, -5.55555556])

#проверка
print('k1=', 4*0.46666667 +2*3.84444444 +1*(-5.55555556))
print('k2=', 1*0.46666667 +3*3.84444444 +0*(-5.55555556))
print('k3=', 0*0.46666667 +5*3.84444444 +4*(-5.55555556))

In [61]:
#Задание 4
#Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
#Остальные столбцы - количество покупок категорий товаров этим пользователем:
#Найдите самого похожего пользователя. 
#Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

#На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine (a, b):
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)
    return np.dot(a, b) / (aLength * bLength)

min_cos = 0
min_cos_row = []
for i in users_stats:
    tmp = cosine(next_user_stats, i)
    if tmp > min_cos: 
        min_cos = tmp
        min_cos_row = i
    
print('Минимальное расстояние = ', min_cos, 'для пользователя с покупками', min_cos_row )



Минимальное расстояние =  0.9486832980505138 для пользователя с покупками [0 1 1 0 0 0]
